*&---------------------------------------------------------------------*
*& Include MZPOS_SEARCH_RETURNI01
*&---------------------------------------------------------------------*

*&SPWIZARD: INPUT MODULE FOR TS 'TABSTRIP_CNTRL'. DO NOT CHANGE THIS LIN
*&SPWIZARD: GETS ACTIVE TAB
MODULE TABSTRIP_CNTRL_ACTIVE_TAB_GET INPUT.
  OK_CODE = SY-UCOMM.
  CASE OK_CODE.
    WHEN C_TABSTRIP_CNTRL-TAB1.
      G_TABSTRIP_CNTRL-PRESSED_TAB = C_TABSTRIP_CNTRL-TAB1.
    WHEN C_TABSTRIP_CNTRL-TAB2.
      G_TABSTRIP_CNTRL-PRESSED_TAB = C_TABSTRIP_CNTRL-TAB2.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.
