*&---------------------------------------------------------------------*
*& Include          ZPOS_PERSIST_PRICELIST_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN: BEGIN OF BLOCK screen.

  SELECTION-SCREEN: BEGIN OF BLOCK main WITH FRAME TITLE TEXT-tf0.

    SELECTION-SCREEN:  BEGIN OF LINE,
    COMMENT 1(15) TEXT-t01 FOR FIELD p_ord.
    SELECTION-SCREEN    POSITION 38.
    PARAMETERS: p_ord TYPE ty_mag_order OBLIGATORY.
    SELECTION-SCREEN: END OF LINE.

    SELECTION-SCREEN:  BEGIN OF LINE,
    COMMENT 1(15) TEXT-t02 FOR FIELD p_delv.
    SELECTION-SCREEN    POSITION 38.
    PARAMETERS: p_delv AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN: END OF LINE.

    SELECTION-SCREEN:  BEGIN OF LINE,
    COMMENT 1(15) TEXT-t04 FOR FIELD p_invt.
    SELECTION-SCREEN    POSITION 38.
    PARAMETERS: p_invt AS CHECKBOX DEFAULT ' '.
    SELECTION-SCREEN: END OF LINE.

    SELECTION-SCREEN:  BEGIN OF LINE,
    COMMENT 1(15) TEXT-t03 FOR FIELD p_pgi.
    SELECTION-SCREEN    POSITION 38.
    PARAMETERS: p_pgi AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN: END OF LINE.

    SELECTION-SCREEN:  BEGIN OF LINE,
    COMMENT 1(15) TEXT-t05 FOR FIELD p_bill.
    SELECTION-SCREEN    POSITION 38.
    PARAMETERS: p_bill AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN: END OF LINE.

    SKIP 1.

    SELECTION-SCREEN:  BEGIN OF LINE,
    COMMENT 1(15) TEXT-t06 FOR FIELD p_flow.
    SELECTION-SCREEN    POSITION 38.
    PARAMETERS: p_flow AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN: END OF LINE.

  SELECTION-SCREEN: END OF BLOCK main.

SELECTION-SCREEN: END OF BLOCK screen.
